### ISSUE TITLE
[arm/v7] Container must run --privileged

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/mtconnect-agent#1]
Buildx arm/v7 image must be started with --privileged, otherwise fails.

goals:
* use buildx for arm7, aarch64, and amd64
* run container as user, not root

```
-- install Docker
sudo apt-get update
sudo apt-install curl
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker $(whoami)
newgrp docker
sudo systemctl enable docker
sudo systemctl start docker
sudo apt install python3-pip
sudo apt-get -y install libffi-dev libssl-dev python3-dev python3 python3-pip
sudo pip3 install docker-compose
sync

-- install buildx
sudo apt install gnupg2 pass
docker login --username ladder99
# after moving from ubuntu20 to ubuntu21 base, to resolve cmake armhf issue
# docker run --privileged --rm tonistiigi/binfmt --install all
docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
docker buildx create --name multiarch --driver docker-container --use
docker buildx inspect --bootstrap
sync

-- clone
git clone https://github.com/Ladder99/mtconnect-agent
cd mtconnect-agent

-- build multi arch
--docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --tag=ladder99/mtconnect-agent:latest tag=ladder99/mtconnect-agent:1.7.0.3 --push .

-- docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --tag=ladder99/mtconnect-agent:chris --push .
docker buildx build --platform linux/amd64 --tag=ladder99/mtconnect-agent:chris --push .
docker buildx build --platform linux/arm64 --tag=ladder99/mtconnect-agent:chris --push .
docker buildx build --platform linux/arm/v7 --tag=ladder99/mtconnect-agent:chris --push .

-- build target arch only
-- docker build --tag=ladder99/mtconnect-agent:latest --tag=ladder99/mtconnect-agent:1.7.0.3 .
-- docker push ladder99/mtconnect-agent

-- run agent + simulator
docker run -it -p 5000:5000 ladder99/mtconnect-agent:latest
-- run agent, no simulator
docker run -it -p 5000:5000 ladder99/mtconnect-agent:latest sh -c "cd /etc/mtconnect/simulator && agent debug agent.cfg"

-- docker compose
docker-compose up -d

-- look into volume
sudo ls /var/lib/docker/volumes/pi_mtc_agent_data/_data/simulator
sudo cat /var/lib/docker/volumes/pi_mtc_agent_data/_data/simulator/agent.cfg
```

test-agent.sh
```
#!/bin/bash

# run the adapter simulator
/usr/bin/ruby /etc/mtconnect/simulator/run_scenario.rb -l \
  /etc/mtconnect/simulator/VMC-3Axis-Log.txt &

# run the agent with sample agent config
cd /etc/mtconnect/simulator && agent debug agent.cfg
```

Dockerfile
```
# MTConnect C++ Agent docker image
# adapted from http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu

# note: removed 'sudo' from commands - ubuntu doesn't recognize it.

#----------------------------------------------------------------------------
# build os
#----------------------------------------------------------------------------

# base image - ubuntu has linux/arm/v7, linux/amd64, etc
FROM ubuntu:21.04 AS compile
# FROM raspbian/stretch AS make-os  # too old
# FROM balenalib/raspberry-pi-debian:build AS make-os  # only arm64

# get dependencies
# note: removed ruby - install in second stage
RUN apt-get update && apt-get install -y \
  git cmake build-essential libxml2 libxml2-dev libcppunit-dev screen curl

#----------------------------------------------------------------------------
# build makefile
#----------------------------------------------------------------------------

# get agent source
RUN mkdir -p ~/agent/build \
  && cd ~/agent \
  && git clone https://github.com/mtconnect/cppagent.git --depth 1

# build makefile using cmake
# note: fails when building for linux/arm/7 in macos docker:
#   CMake Error at /usr/share/cmake-3.16/Modules/CMakeCompilerIdDetection.cmake:26 (list):
#   list sub-command REMOVE_ITEM requires two or more arguments.
# fix with CFLAGS - see https://gitlab.kitware.com/cmake/cmake/-/issues/20568#note_780329
RUN cd ~/agent/build \
  && export CFLAGS="-D_FILE_OFFSET_BITS=64" \
  && export CXXFLAGS="-D_FILE_OFFSET_BITS=64" \
  && cmake -D CMAKE_BUILD_TYPE=Release ../cppagent/

#----------------------------------------------------------------------------
# compile app
#----------------------------------------------------------------------------

# compile source (~20mins - 3hrs)
RUN cd ~/agent/build \
  && make \
  && cp agent/agent /usr/local/bin

# copy simulator
RUN mkdir -p /etc/mtconnect \
  && cd ~/agent/cppagent \
  && cp -r schemas simulator /etc/mtconnect \
  && cp -r styles /etc/mtconnect/styles

# add our stylesheet for the / endpoint
RUN echo "DevicesStyle { Location = /styles/Devices.xsl }" >> /etc/mtconnect/simulator/agent.cfg

#----------------------------------------------------------------------------
# run app
#----------------------------------------------------------------------------

# multi-stage build - bring only essentials from previous layers
FROM ubuntu:21.04

# install ruby for simulator
RUN apt-get update && apt-get install -y ruby

# copy agent app and simulator files to new layer
COPY --from=compile /usr/local/bin/agent /usr/local/bin
COPY --from=compile /etc/mtconnect /etc/mtconnect

# bring in our stylesheets
COPY styles /etc/mtconnect/styles

# bring in test script
COPY test-agent.sh /etc/mtconnect

# expose port
EXPOSE 5000

# change to a new non-root user for better security
RUN groupadd --gid 1000 ladder99 \
  && useradd --gid 1000 --uid 1000 --create-home ladder99
USER ladder99

# default run command - can override with docker run or docker-compose.
# this script runs the app and ruby simulator.
CMD ["/etc/mtconnect/test-agent.sh"]
```

docker-compose.yml
```
version: '3.7'

services:
  agent:
    container_name: mtc_agent
    image: ladder99/mtconnect-agent:latest
    restart: always
    command: [sh, -c, "/usr/bin/ruby /etc/mtconnect/simulator/run_scenario.rb -l /etc/mtconnect/simulator/VMC-3Axis-Log.txt & cd /etc/mtconnect/simulator && agent debug agent.cfg"]
    networks:
      - mtconnect
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mtc_agent_data:/etc/mtconnect
    logging:
      options:
        max-size: '1m'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    networks:
      - mtconnect
    ports:
      - '9000:9000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: 'none'

volumes:
  portainer_data:
  mtc_agent_data:

networks:
  mtconnect:
    name: mtconnect
```
